"""init

Revision ID: ef46d742779f
Revises: 983616fe869f
Create Date: 2023-12-05 14:08:29.883938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef46d742779f'
down_revision: Union[str, None] = '983616fe869f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Products')
    op.drop_table('Users')
    op.drop_table('Orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Orders',
    sa.Column('order_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Orders_order_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['Products.product_id'], name='Orders_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='Orders_user_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', name='Orders_pkey')
    )
    op.create_table('Users',
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Users_user_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='Users_pkey')
    )
    op.create_table('Products',
    sa.Column('product_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Products_product_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('quantity_available', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('product_id', name='Products_pkey')
    )
    # ### end Alembic commands ###
